language: java
 
addons:
  sonarcloud:
    organization: "switcherapi"
    token: ${SONAR_TOKEN}
    
cache:
  directories:
  - $HOME/.m2

deploy:
  provider: heroku
  app: switcher-ac
  api_key: ${HEROKU_API_KEY}

script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=switcherapi_switcher-ac
