language: java

jdk:
  - oraclejdk11

branches:
  only:
  - master
 
addons:
  sonarcloud:
    organization: "switcherapi"
    token: ${SONAR_TOKEN}
    
cache:
  directories:
  - $HOME/.m2

before_deploy:
  - rvm $(travis_internal_ruby) --fuzzy do ruby -S gem install faraday -v 1.9.3
deploy:
  provider: heroku
  app: switcher-ac
  api_key: ${HEROKU_API_KEY}

script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=switcherapi_switcher-ac
