name: Main Workflow

on:
  push:
    branches:
      - master
  pull_request:
      types: [opened, synchronize, reopened]

jobs:
  build:
    runs-on: ubuntu-latest
    if: "! contains(toJSON(github.event.commits.*.message), '[skip ci]')"

    steps:
    - uses: actions/checkout@v2
    - name: 'Set up JDK 11'
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'
        fetch-depth: 0
        cache: maven
    - name: 'Build with Maven'
      run: mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=switcherapi_switcher-ac
      
    - name: 'SonarCloud Scan'
      uses: sonarsource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

