name: Master Branch

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    if: "! contains(toJSON(github.event.commits.*.message), '[skip ci]')"

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: 'temurin'
          cache: maven
      - name: Maven Package
        run: mvn -B clean package -DskipTests

  test_analyze:
    name: Test & Analyze
    needs: [ build ]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: 'temurin'
          cache: maven
      - name: Test & SonarCloud Scan
        run: mvn -B clean verify -Pcoverage,sonar -Dsonar.login=${{ secrets.SONAR_TOKEN }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  deploy:
    name: Deploy
    needs: [ test_analyze ]
    runs-on: ubuntu-latest
    if: success() && github.ref == 'refs/heads/master'
    
    steps:
      - uses: actions/checkout@v2
      - name: 'Deploy'
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY_2}}
          heroku_app_name: "switcher-ac"
          heroku_email: "switcher.project@gmail.com"
